version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      PG_HOST: $PG_HOST
      PG_PORT: 5432
      PG_DATABASE: $PG_DATABASE
      PG_USER: $PG_USER
      PG_PASSWORD: $PG_PASSWORD
    depends_on:
      - postgres
  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes:
      - node_db_data:/var/lib/postgresql/data

volumes:
  node_db_data: {}
